---
title: Opening Notes
author: Joseph Osborne
date: '2021-05-27'
slug: opening-notes
categories: []
tags: []
---

This is a quick introductory post to explain the purpose of this site, and to provide some idea of what to expect in the (hopefully) not too distant future....

## Why?

Why does this site exist? It exists as an attempt to introduce a greater factor of futurist thinking to our lives. It has long been a conclusion of mine, and others I've held conversations with, that as a quirk of both human nature and the structure of our society, we are often inappropriately consumed with the short term aspects of life and politics. 

Scandals and drama are a dime a dozen and a flash in the pan, and when we broach the longer term ideas, we become beset by depressing features. 
One could be excused for thinking that humanity is doomed to make smart long term decisions only by accident. Thankfully, many of us live in a society where a popular upswell, if maintained and channeled, can make nearly any change we could want. 

The difficulty, then, comes in manifesting and maintaining popular enthusiasm for issues which are glacial in nature, extraordinarily slow, and really quite dull even if its bearing down on your house. 

## How (and What)?

Another, more recent conclusion I've come to, is that people generally want to make the right decision. And many people are worried about what the future might hold, for themselves and their families. The key then, is in providing the means to take action in the right direction. 

There are a lot of angles to 'Futurism', but possibly the most impactful one is political, and that is the primary tool which I'll be trying to use to make a change. 

Generally speaking, long term issues are easy to make promises on, and easy to break promises on. You can stand on a stage, or speak on a show, about your grand vision for long term investment, but by the time it either comes to fruition, or turns out your were full of it.... 20 years of life has been lived, and you've lost or won 4 elections without it ever being a factor. And when it does come out, the impact on your reputation is minimal, since your career is either nearly over, or you've got a rich history of other, more pressing successes or failures on record.

A lot of it comes down to time, the general populace, has a shortage of the kind of time, energy, money and skills required to actually keep track of what their politicians have said, to keep track of the issues they promise to fix, and to keep track of if their policy is actually doing anything.

I aim to build a platform which will make that simpler. By tracking a variety of long term issues affecting us, in as granular a way as I can source, the aim is to make understanding how the situation is evolving easier. 

Once we have tracking of the issues, then we want to track the plans, which politicians have made promises on what issue, and what areas would they have power to affect.

Then we can track activity...

And this is where the Futurist Voters association really must lean into the name, since at that point it will begin to resemble an interest group. Though not one focused around narrow industrial or cultural interests. We would be interacting with politicians aroudnd the country, througout the lifecycle of politics. Suggesting good policies, chasing up of manifesto pledges of those policies, and iterating on what makes a good futurist policy, using learnings from all the harassment we are doing.

## Coming Soon

In the coming days and weeks, expect to see further articles, clarifying the kind of issues which we want to track, detailing the plans for how the Association will evolve, and possibly most importantly, discussing the ways that you can get involved!
